# Generated by Django 4.2.9 on 2024-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('C', 'C'), ('javascript', 'Javascript')], default='python', max_length=20),
        ),
    ]
