# Generated by Django 4.2.9 on 2024-01-29 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobtest', '0002_question_code_question_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(verbose_name='time ended'),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(verbose_name='time started'),
        ),
    ]
