# Generated by Django 4.2.9 on 2024-01-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobtest', '0004_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answer',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobtest.question'),
        ),
    ]
